# Generated by Django 3.0.5 on 2020-07-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'email')},
        ),
    ]
